name: Deploy changes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_URI: europe-southwest1-docker.pkg.dev/ds-2025-g51-private-messages/frontend/production:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate in Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ds-2025-g51-private-messages

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t "$IMAGE_URI" ./frontend
          docker push "$IMAGE_URI"

  docker-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JUMPSELLER: ${{ secrets.JUMPSELLER }}
      PUBSUB: ${{ secrets.PUBSUB }}
      PASSWORD: ${{ secrets.PASSWORD1 }}
      SALT: ${{ secrets.PASSWORD2 }}
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_URI: europe-southwest1-docker.pkg.dev/ds-2025-g51-private-messages/backend/production:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate in Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ds-2025-g51-private-messages

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build --secret id=JUMPSELLER --secret id=PUBSUB --secret id=PASSWORD --secret id=SALT -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

  terraform:
    needs:
      - docker-frontend
      - docker-backend
    runs-on: ubuntu-latest
    
    env:
      FRONTEND_IMAGE: europe-southwest1-docker.pkg.dev/ds-2025-g51-private-messages/frontend/production:${{ github.sha }}
      BACKEND_IMAGE: europe-southwest1-docker.pkg.dev/ds-2025-g51-private-messages/backend/production:${{ github.sha }}

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate in Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -var "frontend_image=${{ env.FRONTEND_IMAGE }}" -var "backend_image=${{ env.BACKEND_IMAGE }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var "frontend_image=${{ env.FRONTEND_IMAGE }}" -var "backend_image=${{ env.BACKEND_IMAGE }}"
